import { DemoUser, DemoRequest, DemoComment, DemoActivityLog } from './types'

export const DEMO_USERS: Record<string, DemoUser> = {
  // Students
  'student-1': {
    id: 'student-1',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@campus.edu',
    studentId: 'STU2026001',
    year: '3rd Year',
    hostel: 'Block A',
    room: 'A-204',
    role: 'STUDENT',
  },
  'student-2': {
    id: 'student-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@campus.edu',
    studentId: 'STU2026002',
    year: '2nd Year',
    hostel: 'Block B',
    room: 'B-118',
    role: 'STUDENT',
  },
  'student-3': {
    id: 'student-3',
    name: 'Rahul Kumar',
    email: 'rahul.kumar@campus.edu',
    studentId: 'STU2026003',
    year: '4th Year',
    hostel: 'Block C',
    room: 'C-312',
    role: 'STUDENT',
  },

  // Staff
  'staff-1': {
    id: 'staff-1',
    name: 'Vikram Rao',
    employeeId: 'EMP202601',
    email: 'vikram.rao@campus.edu',
    department: 'IT Support',
    specialization: 'Network, Wi-Fi, Computers, Internet',
    role: 'STAFF',
  },
  'staff-2': {
    id: 'staff-2',
    name: 'Suresh Kumar',
    employeeId: 'EMP202602',
    email: 'suresh.kumar@campus.edu',
    department: 'Electrical',
    specialization: 'Electrical systems, power, lights, switches, wiring',
    role: 'STAFF',
  },
  'staff-3': {
    id: 'staff-3',
    name: 'Anjali Devi',
    employeeId: 'EMP202603',
    email: 'anjali.devi@campus.edu',
    department: 'Hostel',
    specialization: 'Hostel maintenance, plumbing, cleaning, room facilities',
    role: 'STAFF',
  },

  // Admin
  'admin-1': {
    id: 'admin-1',
    name: 'Admin Office',
    employeeId: 'ADMIN001',
    email: 'admin@campus.edu',
    department: 'Campus Administration',
    role: 'ADMIN',
  },
}

export const INITIAL_DEMO_REQUESTS: DemoRequest[] = [
  {
    id: 'req-1008',
    ticketNumber: 'CR-1008',
    title: 'Internet completely unavailable',
    studentId: 'student-1',
    studentName: 'Arjun Reddy',
    category: 'IT Support',
    priority: 'CRITICAL',
    location: 'Hostel Block A',
    building: 'Block A',
    room: '2nd Floor Wing',
    status: 'SUBMITTED',
    department: 'IT Support',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // 45 mins ago
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    description:
      'No internet connection across the entire second floor of Hostel Block A. Both LAN ports and wireless access points have red blinking LED indicators. Urgent as students have online examinations.',
    aiRecommendation: {
      category: 'IT Support',
      priority: 'CRITICAL',
      department: 'IT Support',
      suggestedStaff: 'Vikram Rao',
      summary: 'Catastrophic floor-wide network outage in Hostel Block A affecting multiple students.',
      reasoning: 'Red blinking router indicators and floor-wide impact warrant highest severity SLA response.',
    },
  },
  {
    id: 'req-1001',
    ticketNumber: 'CR-1001',
    title: 'Wi-Fi not working in Hostel Block A',
    studentId: 'student-1',
    studentName: 'Arjun Reddy',
    category: 'IT Support',
    priority: 'HIGH',
    location: 'Hostel Block A',
    building: 'Hostel Block A',
    room: 'A-204',
    status: 'IN_PROGRESS',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Vikram Rao',
    department: 'IT Support',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    description:
      'The Wi-Fi connection in my room has been unstable since yesterday. It connects for a few seconds and then disconnects. Other students on the same floor are also experiencing the issue.',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    aiRecommendation: {
      category: 'IT Support',
      priority: 'HIGH',
      department: 'IT Support',
      suggestedStaff: 'Vikram Rao',
      summary: 'Network connectivity and repeated Wi-Fi packet drops in residential block.',
      reasoning: 'Multiple reported drops on floor cluster indicates access point hardware degradation.',
    },
  },
  {
    id: 'req-1003',
    ticketNumber: 'CR-1003',
    title: 'Water leakage in hostel bathroom',
    studentId: 'student-3',
    studentName: 'Rahul Kumar',
    category: 'Plumbing',
    priority: 'HIGH',
    location: 'Hostel Block C',
    building: 'Hostel Block C',
    room: 'C-312',
    status: 'SUBMITTED',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Anjali Devi',
    department: 'Hostel',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    description:
      'There is continuous water leakage under the bathroom sink and the floor is getting wet. Valve appears stuck.',
    aiRecommendation: {
      category: 'Plumbing',
      priority: 'HIGH',
      department: 'Hostel',
      suggestedStaff: 'Anjali Devi',
      summary: 'Uncontrolled water leak in residential restroom fixture.',
      reasoning: 'Continuous water pooling poses slip hazard and structural water seepage risk.',
    },
  },
  {
    id: 'req-1002',
    ticketNumber: 'CR-1002',
    title: 'Ceiling light not working',
    studentId: 'student-2',
    studentName: 'Priya Sharma',
    category: 'Electrical',
    priority: 'MEDIUM',
    location: 'Academic Block B',
    building: 'Academic Block B',
    room: 'B-204',
    status: 'ASSIGNED',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Suresh Kumar',
    department: 'Electrical',
    createdAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    description:
      'The ceiling light in classroom B-204 is not working. The fixture buzzed loudly this morning before going out completely.',
    aiRecommendation: {
      category: 'Electrical',
      priority: 'MEDIUM',
      department: 'Electrical',
      suggestedStaff: 'Suresh Kumar',
      summary: 'Burnt-out ballast or bulb in classroom luminaire.',
      reasoning: 'Audible buzzing suggests ballast capacitor failure requiring electrical tech intervention.',
    },
  },
  {
    id: 'req-1005',
    ticketNumber: 'CR-1005',
    title: 'Broken hostel door lock',
    studentId: 'student-2',
    studentName: 'Priya Sharma',
    category: 'Hostel',
    priority: 'HIGH',
    location: 'Hostel Block B',
    building: 'Hostel Block B',
    room: 'B-118',
    status: 'ASSIGNED',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Anjali Devi',
    department: 'Hostel',
    createdAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    description:
      'The main latch lock on the room door is loose and key gets jammed inside cylinder. Safety concern at night.',
    aiRecommendation: {
      category: 'Hostel',
      priority: 'HIGH',
      department: 'Hostel',
      suggestedStaff: 'Anjali Devi',
      summary: 'Lock latch malfunction impeding room security.',
      reasoning: 'Student room security vulnerability requires high priority same-day lock replacement.',
    },
  },
  {
    id: 'req-1006',
    ticketNumber: 'CR-1006',
    title: 'Classroom fan making loud noise',
    studentId: 'student-3',
    studentName: 'Rahul Kumar',
    category: 'Electrical',
    priority: 'MEDIUM',
    location: 'Mechanical Block',
    building: 'Mechanical Block',
    room: 'ME-204',
    status: 'IN_PROGRESS',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Suresh Kumar',
    department: 'Electrical',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    description:
      'Ceiling fan #2 in classroom ME-204 wobbles severely at high speeds and makes a grinding metal noise.',
    aiRecommendation: {
      category: 'Electrical',
      priority: 'MEDIUM',
      department: 'Electrical',
      suggestedStaff: 'Suresh Kumar',
      summary: 'Bearing worn out in classroom ceiling fan.',
      reasoning: 'Grinding noise points to defective motor bearing needing lubrication or blade balance.',
    },
  },
  {
    id: 'req-1004',
    ticketNumber: 'CR-1004',
    title: 'Projector not working in CS-301',
    studentId: 'student-1',
    studentName: 'Arjun Reddy',
    category: 'IT Support',
    priority: 'MEDIUM',
    location: 'Computer Science Block',
    building: 'CS Block',
    room: 'CS-301',
    status: 'RESOLVED',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Vikram Rao',
    department: 'IT Support',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    description: 'HDMI input gives no display on ceiling projector during lab classes.',
    resolutionNote: 'Replaced faulty 10m high-speed HDMI extension cable in podium harness and tested 4K output.',
    aiRecommendation: {
      category: 'IT Support',
      priority: 'MEDIUM',
      department: 'IT Support',
      suggestedStaff: 'Vikram Rao',
      summary: 'Classroom display input signal failure.',
      reasoning: 'Signal drop typically indicates bad wall-plate cabling or projector EDID handshake failure.',
    },
  },
  {
    id: 'req-1007',
    ticketNumber: 'CR-1007',
    title: 'Garbage collection delayed',
    studentId: 'student-2',
    studentName: 'Priya Sharma',
    category: 'Cleaning',
    priority: 'LOW',
    location: 'Hostel Block B',
    building: 'Hostel Block B',
    room: 'Common Corridor',
    status: 'CLOSED',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Anjali Devi',
    department: 'Hostel',
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    assignedAt: new Date(Date.now() - 60 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    description: 'Corridor dustbins overflowing on floor 1.',
    resolutionNote: 'Housekeeping crew cleared all corridor bins and sanitized the disposal stations.',
    aiRecommendation: {
      category: 'Cleaning',
      priority: 'LOW',
      department: 'Hostel',
      suggestedStaff: 'Anjali Devi',
      summary: 'Sanitation and waste clearance schedule lapse.',
      reasoning: 'Routine facility cleaning task without immediate safety hazard.',
    },
  },
]

export const INITIAL_DEMO_COMMENTS: DemoComment[] = [
  {
    id: 'c-1',
    requestId: 'req-1001',
    userId: 'staff-1',
    authorName: 'Vikram Rao',
    authorRole: 'STAFF',
    content: 'Checked access point on second floor. Network controller shows intermittent connectivity with access point AP-04.',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'c-2',
    requestId: 'req-1001',
    userId: 'student-1',
    authorName: 'Arjun Reddy',
    authorRole: 'STUDENT',
    content: 'Thanks Vikram! The signal is showing 1 bar right now in room A-204.',
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
]

export const INITIAL_DEMO_LOGS: Record<string, DemoActivityLog[]> = {
  'req-1001': [
    {
      id: 'log-1',
      requestId: 'req-1001',
      action: 'Request submitted by Arjun Reddy',
      userName: 'Arjun Reddy',
      timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    },
    {
      id: 'log-2',
      requestId: 'req-1001',
      action: 'AI Triage completed: Suggested Vikram Rao (IT Support)',
      userName: 'System AI',
      timestamp: new Date(Date.now() - 4 * 3600 * 1000 + 10000).toISOString(),
    },
    {
      id: 'log-3',
      requestId: 'req-1001',
      action: 'Assigned to Vikram Rao by Admin Office',
      userName: 'Admin Office',
      timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    },
    {
      id: 'log-4',
      requestId: 'req-1001',
      action: 'Status updated to IN_PROGRESS by Vikram Rao',
      userName: 'Vikram Rao',
      timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    },
  ],
}
